import { useMemo, useState } from "react";

import catalogue from "@site/src/data/pack-catalogue.json";

import styles from "./styles.module.css";

// The catalogue of downloadable packs, rendered from the shipped manifest.
//
//   <PackCatalogue group="languages" labels={{ …translated strings… }} />
//
// The data is generated by webdoc/scripts/build-pack-catalogue.mjs from
// data/bundles.json, so this page cannot describe a catalogue the project does
// not ship. Every word the READER sees that is not a pack's own name comes in
// through `labels`, because the page exists in three languages and the pack
// names and category names do not get translated — they are addresses.

function Bytes({ value, unit }) {
  if (value === null || value === undefined) return null;
  const kb = value / 1024;
  const shown =
    kb >= 1024 ? `${(kb / 1024).toFixed(1)} MB` : `${Math.round(kb)} ${unit}`;
  return <span className={styles.size}>{shown}</span>;
}

function Pack({ pack, labels }) {
  return (
    <details className={styles.pack}>
      <summary className={styles.summary}>
        <span className={styles.name}>{pack.name}</span>
        <code className={styles.id}>{pack.id}</code>
        <Bytes value={pack.bytes} unit={labels.kb} />
      </summary>
      <div className={styles.body}>
        <p className={styles.blurb}>{pack.blurb}.</p>
        {pack.categories.length > 0 && (
          <>
            <p className={styles.label}>
              {labels.holds}
              {pack.truncated ? ` ${labels.andMore}` : ""}
            </p>
            <ul className={styles.categories}>
              {pack.categories.map((c) => (
                <li key={c}>
                  <code>{c}</code>
                </li>
              ))}
            </ul>
          </>
        )}
        <p className={styles.label}>{labels.install}</p>
        <pre className={styles.install}>
          <code>tdcv2 pack add {pack.id}</code>
        </pre>
      </div>
    </details>
  );
}

export default function PackCatalogue({ group, labels }) {
  const packs = catalogue[group] ?? [];
  const [query, setQuery] = useState("");

  const shown = useMemo(() => {
    const q = query.trim().toLowerCase();
    if (!q) return packs;
    return packs.filter(
      (p) =>
        p.id.includes(q) ||
        p.name.toLowerCase().includes(q) ||
        p.categories.some((c) => c.toLowerCase().includes(q)),
    );
  }, [packs, query]);

  return (
    <div className={styles.catalogue}>
      <div className={styles.controls}>
        <input
          className={styles.filter}
          type="search"
          value={query}
          placeholder={labels.filter}
          onChange={(e) => setQuery(e.target.value)}
          aria-label={labels.filter}
        />
        <span className={styles.count}>
          {shown.length === packs.length
            ? `${packs.length} ${labels.total}`
            : `${shown.length} / ${packs.length}`}
        </span>
      </div>
      {shown.length === 0 ? (
        <p className={styles.empty}>{labels.none}</p>
      ) : (
        shown.map((p) => <Pack key={p.id} pack={p} labels={labels} />)
      )}
    </div>
  );
}
