// @ts-check

// The docs sidebar is generated automatically from the folder structure under
// docs/. Category labels and order come from each folder's _category_.json;
// page order comes from `sidebar_position` in each page's front matter.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
