import { describe, expect, it } from 'vitest';

import { createPrng, cyrb128, sfc32 } from '../../src/prng/prng.js';

/**
 * Bit-identical reference values captured by running the 2022-2024 TDC
 * prototype's PRNG (src/generator/Generator.ts, pseudoRandom()) from
 * `/Users/.../tdc/`. Any regression in these values — in this or in
 * any future Python/Java port — means we've broken the deterministic
 * output contract. See docs/vision/16-portability.md.
 *
 * DO NOT EDIT the numeric values unless you are consciously breaking
 * backward compatibility with files generated by prior TDC versions.
 */
const GOLDEN_VECTORS: { seed: string; first10: readonly number[] }[] = [
  {
    seed: 'hello',
    first10: [
      0.9664666061289608, 0.7261954692658037, 0.9365882698912174, 0.7168871473986655,
      0.8954141286667436, 0.8551938948221505, 0.8258442885708064, 0.47843142435885966,
      0.32094397651962936, 0.28511247923597693,
    ],
  },
  {
    seed: 'tdc-test-seed',
    first10: [
      0.10674650920554996, 0.6157257244922221, 0.7778954920358956, 0.5976110324263573,
      0.8827297291718423, 0.4734369060024619, 0.7653657766059041, 0.3167362285312265,
      0.5539481402374804, 0.9725872124545276,
    ],
  },
  {
    // The seed used by all five canonical fixtures in fixtures/*.xml.
    seed: '674teyer74yTRGY7',
    first10: [
      0.30582878552377224, 0.012814311310648918, 0.8610370121896267, 0.6619220457505435,
      0.738723217509687, 0.650009837700054, 0.0017171241343021393, 0.5372903295792639,
      0.7135875003878027, 0.8677765380125493,
    ],
  },
  {
    seed: '',
    first10: [
      0.7160958386957645, 0.4519506280776113, 0.29120085295289755, 0.4638126480858773,
      0.013523319270461798, 0.9874513826798648, 0.8728331718593836, 0.7227669642306864,
      0.5459710345603526, 0.847082560416311,
    ],
  },
  {
    seed: 'a',
    first10: [
      0.7573448994662613, 0.8936707871034741, 0.3226523417979479, 0.7466451760847121,
      0.9382210180629045, 0.3177623376250267, 0.9535233662463725, 0.9264111374504864,
      0.30480425409041345, 0.16784215602092445,
    ],
  },
  {
    seed: 'longer-seed-with-digits-123',
    first10: [
      0.5112187373451889, 0.5440724114887416, 0.9178853079210967, 0.8593992555979639,
      0.16273200511932373, 0.7251239062752575, 0.6353178767021745, 0.2987366996239871,
      0.4826492324937135, 0.7687776908278465,
    ],
  },
];

describe('cyrb128 hash', () => {
  it('returns exactly four numbers', () => {
    const result = cyrb128('hello');
    expect(result).toHaveLength(4);
  });

  it('every output is a non-negative 32-bit integer', () => {
    const result = cyrb128('hello');
    for (const n of result) {
      expect(Number.isInteger(n)).toBe(true);
      expect(n).toBeGreaterThanOrEqual(0);
      expect(n).toBeLessThanOrEqual(0xffffffff);
    }
  });

  it('is deterministic — same input gives same output', () => {
    expect(cyrb128('seed')).toEqual(cyrb128('seed'));
  });

  it('handles empty string', () => {
    const result = cyrb128('');
    expect(result).toHaveLength(4);
  });

  it('different seeds diverge', () => {
    expect(cyrb128('seed-a')).not.toEqual(cyrb128('seed-b'));
  });
});

describe('sfc32 generator', () => {
  it('yields floats strictly inside [0, 1)', () => {
    const prng = sfc32(1, 2, 3, 4);
    for (let i = 0; i < 1000; i++) {
      const v = prng();
      expect(v).toBeGreaterThanOrEqual(0);
      expect(v).toBeLessThan(1);
    }
  });

  it('is deterministic given the same state', () => {
    const a = sfc32(1, 2, 3, 4);
    const b = sfc32(1, 2, 3, 4);
    for (let i = 0; i < 50; i++) {
      expect(a()).toBe(b());
    }
  });

  it('diverges with different state', () => {
    const a = sfc32(1, 2, 3, 4);
    const b = sfc32(1, 2, 3, 5);
    const aFirst = a();
    const bFirst = b();
    expect(aFirst).not.toBe(bFirst);
  });
});

describe('createPrng — bit-identical reference vectors', () => {
  it.each(GOLDEN_VECTORS)(
    'seed $seed reproduces first 10 values from the 2022-2024 prototype',
    ({ seed, first10 }) => {
      const prng = createPrng(seed);
      for (const expected of first10) {
        expect(prng()).toBe(expected);
      }
    },
  );

  it('seed string is the only state input — two prngs from the same seed diverge independently', () => {
    const a = createPrng('x');
    const b = createPrng('x');
    // Drain a without touching b
    for (let i = 0; i < 5; i++) a();
    // b still produces the "first" value for this seed
    const bFirst = b();
    const aFresh = createPrng('x')();
    expect(bFirst).toBe(aFresh);
  });

  it('output is a full 32-bit fraction (many distinct values)', () => {
    const prng = createPrng('variety');
    const seen = new Set<number>();
    for (let i = 0; i < 1000; i++) seen.add(prng());
    expect(seen.size).toBeGreaterThan(990);
  });
});
