//! Generated by `scripts/bundle-packs.mjs`. Do not edit.
//!
//! Empty in a checkout: there the packs are on disk at the repository root, and
//! reading them from there is what keeps this implementation and the other four
//! looking at the very same bytes. `bundle-packs.mjs add` fills this in for the
//! published crate, where there is no repository to walk up to.

/// Every bundled pack file: its address-bearing path, and its contents.
pub const FILES: &[(&str, &str)] = &[];
